### ISSUE TITLE
Manque des notes de la mélodie

### ISSUE THREAD

**Issue by Chris-afk71** [Jean-Romain/tabliato#12]
Bonjour,
Merci pour la version audio, c'est super.
Il me semble qu'il y a un problème dans le rendu audio avec les notes pointés, on entend bien les B/A mais il manque la mélodie.
quand on descend le tempo ça parait flagrant, après je ne suis pas très fort en solfège et je l'ai peut être mal écrit...
```
3/4 
Rythme B a a 
Tempo Noir 120
{
  p5:2 t4:4 G
  p4:2 5:4 G
  6:2 t7:4 G
  p7:2. E
  t7:2 p6:4 D
  t5:2. A
  4:2. D 
  ~ 4:2 p6:4 D

\break
  
  t6:2 5:4 D
  p5:2 6:4 G
  t7:2 p7:4 A
  t8:2. D
  6 D
  p6:2. G 
  ~ 6:2 6:4 G

\break

  p6:2 t6:4 G
  5:2. A
  4:2. D
  p6:4 t6 5 G
  p5:2. G
  4 G
  ~ 4:2 5:4 G
  t6:2 5:4 D

\break

  p5:2. G
  7 G
  t7:2 p7:4 A
  t7:4 p6:2 D
  ~ 6:2. G
}
```

**Comment by Jean-Romain** [comment]
Hé bien... pas facile d'expliquer un problème de rendu audio à l'écrit je vous l'accorde mais pouvez vous essayer de mieux m'expliquer le problème ? En ce qui me concerne je connais assez mal le solfège aussi et en plus ma capacité à *entendre la musique et le rythme* est nulle. Je suis un bien mauvais accordéoniste débutant. Je programme mieux que je ne joue, c'est pour ca que j'ai besoin de tabliato ! Donc vous pouvez (devez en fait) m'expliquer votre problème avec des mots simple sans utiliser trop de notions de solfège avancées :wink: 

Mais je crois comprendre ce que vous voulez dire. Je viens d'essayer à noire = 60 et en effet les notes longues s'estompent rapidement après la basse. Ensuite les deux accords sont joués sans la note de la mélodie. Avec un tempo plus rapide on n'entend pas ça (et j'ai du mal à l'entendre déjà à 60 mais ca c'est à cause de ma mauvaise oreille musicale je pense).

Réessayez avec le rendu <kbd>Accordion.sf2</kbd> à la place de <kbd>Loffet.sf2</kbd> (je suppose que vous avez utilisé Loffet comme je l'ai suggéré). Le problème disparaît. En tout ça je crois que oui. En fait ca s'explique bien. On parle ici de rendu numérique de la musique.  <kbd>Accordion.sf2</kbd> doit être une bibliothèque de sons synthétique simples (et donc moche) et infinis dans le temps (ou très long au moins). Alors que <kbd>Loffet.sf2</kbd> est une bibliothèque de vrai sons d'accordéon enregistrés et fini dans le temps. Donc je dirais que a `t = 60` chaque note est tellement longue que ça dépasse la durée des notes de la bibliothèque <kbd>Loffet.sf2</kbd> mais pas de  <kbd>Accordion.sf2</kbd>.

Donc ma réponse c'est que tout semble allez bien. Jouez la musique à un tempo normal et voilà :wink:

**Comment by Chris-afk71** [comment]
ok merci, j'ai testé avec accordion (en mono) ça fonctionne.
