### ISSUE TITLE
Ligne de tenue à la main gauche

### ISSUE THREAD

**Issue by Jean-Romain** [Jean-Romain/tabliato#14]
Ajouter des barres indiquant la tenue des accords main gauche lorsque ceux-ci ne sont pas conforme au rythme normal. Exemple:

![](https://user-images.githubusercontent.com/102148143/160107062-d1f4841b-3728-408f-9590-c24b775684bb.png)

**Comment by Chris-afk71** [comment]
on est dans le même cas ci dessous ou c'est possible déjà de l'écrire ?

![image](https://user-images.githubusercontent.com/102148143/160230596-e88bf9cd-db83-4a4f-8e67-fe0d4b304ce6.png)

**Comment by Jean-Romain** [comment]
C'est possible de l'écrire et de le jouer mais ça ne sera pas rendu visuellement avec des barres. C'est la prochaine fonctionnalité sur laquelle je vais travailler.

**Comment by Jean-Romain** [comment]
Dans la prochaine version 

```ly
\partial 2*8 t5:4 [r:4]

\motif [B:2.]

t7:4. 6':8 8 7 A
p7:4. 6':8 8 7 G
t8:4. 7':8 9 8 F
t7':4. 9:8 8' 7' G

\break

p7':4. 8':8 7' 6' C
p8':4. 7':8 8' 7 G
t8':4. 7':8 8' 7 A
\motif [B:8 r:8 a:8 r:8 a:8 r:8]
p 7 4' 7 8 6' 7 E

\break

t 7:4 7:8 6' 8 7 A
p 7:4 7:8 6' 8 7 G
t 8:4 8:8 7' 9 8 F
7' 9 8' 9' 8' 7' G
```

![Capture d’écran du 2022-04-01 20-22-07](https://user-images.githubusercontent.com/3872279/161356565-18a8c68f-508b-4d93-a335-fe2913843d1e.png)

**Comment by Chris-afk71** [comment]
Bonjour,
J'ai installé la version 1.0.3 et copier / coller le code ci dessus et ça ne donne pas la même chose chez moi...
Pourquoi ?

![image](https://user-images.githubusercontent.com/102148143/161516685-a7d15a9e-30af-4647-a105-edb3a3c3ad2a.png)

**Comment by Jean-Romain** [comment]
Il faut se mettre en 3/4 rythme B a a

**Comment by Chris-afk71** [comment]
Bonjour,
Ca ne marche pas chez moi avec la version 1.03.

![image](https://user-images.githubusercontent.com/102148143/162144861-3fa45614-8c80-43aa-a7d1-80bf739458e1.png)

et si j'ouvre celle déjà faite avant et que je compile j'ai un décalage

![image](https://user-images.githubusercontent.com/102148143/162145215-b8f54db9-9303-4bcf-b92a-36b15169f926.png)

si je repasse en version 1.02 ça remarche (la deuxième)...

une idée sur ce que j'ai fait de travers ?

**Comment by Jean-Romain** [comment]
Mmm ...je peux voir le code exacte de la première? et de la deuxième?

**Comment by Chris-afk71** [comment]
**Première :** 
\set Timing.beamExceptions = #'()
\set Timing.beatStructure=2,2,2 

\partial 4 t5:4 [r:4]

\motif [B:2.]

t7:4. 6':8 8 7 A
p7:4. 6':8 8 7 G
t8:4. 7':8 9 8 F
t7':4. 9:8 8' 7' G

\break

p7':4. 8':8 7' 6' C
p8':4. 7':8 8 7 G
t8':4. 7':8 8 7 A
\motif [B:8 r:8 a:8 r:8 a:8 r:8]
p 7 4' 7 8 6' 7 E

\break

t 7:4 7:8 6' 8 7 A
p 7:4 7:8 6' 8 7 G
t 8:4 8:8 7' 9 8 F
7' 9 8' 9' 8' 7' G

**Deuxième :** 
\repeat volta 2 
{
  t9:4 7' 8
  6' 8 6'
  7 6' 8
  9:2 9:4	
  p8:4 7' 8
  6' 7 5
  7 6' 8
  7:2 7:4

   A A A A G G E E 
  
\break
  
  t7:4 7' 8
  6' 7 6'
  7 7' 8
  p7:2.
  t7:4 8 7'
  p7':2.
  8:4 7 6'
  t7:2. 

   A G F E A C G A
}

\repeat volta 2 
{
  t9:2 8':4
  9:2 9:4 
  p8:2 7':4
  8:2 8:4
  t7:4 8 6'
  7:2 4':4
  p4':4 7 8
  7':2.

   A A G G F F E E 
  
\break
  
  t9:2 7':4
  9 8' 9
  p8:2 6':4
  8 7' 8
  t7 7' 8
  p7 7' 8
  8 6' 7
  t7:2.

   A A G G F E E A
}

**Comment by Jean-Romain** [comment]
Les deux fonctionnent parfaitement bien chez moi. Je vais faire un test avec la version windows. Il y a peut être un bug spécifique sous windows. Mais auquel cas toutes les tablatures devraient toutes être fausses je suppose. Pour la deuxième vous être bien sûr d'avoir défini le motif à `B a a` ?

**Comment by Chris-afk71** [comment]
oui le motif est bien B a a, je confirme que toutes celles que j'avais faites ne marche plus dans la V1.03 du coup je suis repassé en V1.02.

**Comment by Jean-Romain** [comment]
C'est corrigé dans la version 1.0.4 normalement. Le bug venait du fait que j'ai changé des fichiers de configurations mais que c'était les anciens qui étaient inclus dans la version Windows.
