### ISSUE TITLE
Lecture audio et visuel

### ISSUE THREAD

**Issue by Chris-afk71** [Jean-Romain/tabliato#17]
Ca serait bien si on avait un marqueur visuel dans la partie tablature et / ou prévisualisation de l'avancement de l'écoute.
Comme un rond autour de la note joué ou autre.

**Comment by Jean-Romain** [comment]
Oui je suis d'accord mais c'est non. C'est beaucoup trop compliqué à faire et si c'est (peut être) techniquement possible j'en suis totalement incapable. J'aimerais moi même avoir cette fonctionnalité mais ça n'arrivera pas désolé.

**Comment by Jean-Romain** [comment]
Je ré-ouvre. Je travaille présentement sur des fonctionnalités vraiment très cool et je pense que c'est pas si impossible à faire.

**Comment by Jean-Romain** [comment]
Voici une idée de ce que ça va rendre. Il faut l'imaginer avec la musique :notes:
 
![music-tracking](https://user-images.githubusercontent.com/3872279/162620281-2843c35a-3855-445d-815b-267fcc24ad7a.gif)

**Comment by Chris-afk71** [comment]
c'est génial comme ça 👍

**Comment by Jean-Romain** [comment]
Et toute les notes seront cliquables pour aller a la ligne de code correspondante. Et chaque ligne de code surlignera les notes correspondantes dans la tablature.

![linkin](https://user-images.githubusercontent.com/3872279/162634176-aeea1359-b54f-45cb-b77e-f9bfbe4ee02a.gif)

**Comment by Jean-Romain** [comment]
Fonctionnalité implémentée

**Comment by nmetifiot** [comment]
Bonjour, je viens de télécharger la release 1.3.3 et cette fonctionnalité ne fonctionne pas. La lecture audio ne se lance pas et le curseur ne bouge pas.
Est-ce qu'il y a eu une régression depuis l'implémentation de la fonctionnalité ?
