### ISSUE TITLE
Liste déroulante de mesures trop petit et illisible

### ISSUE THREAD

**Issue by Chris-afk71** [Jean-Romain/tabliato#19]
il faudrait agrandir un peu le champ mesure, on n'arrive pas à lire :

![image](https://user-images.githubusercontent.com/102148143/160231073-dde42050-2ce2-404c-b7f3-9d10fcebeb30.png)

**Comment by Jean-Romain** [comment]
Ok c'est bizarre normalement ça fait automatiquement la bonne taille je vais regarder. Vous êtes sous Windows 10 ?

**Comment by Chris-afk71** [comment]
Oui Windows 10

**Comment by Jean-Romain** [comment]
Est ce que je peux avoir plus d'info. Je n'ai pas ce problème.

- Résolution d'écran
- Est ce la fenêtre tabliato est ouvert en grand
- Screenshoot complet
- Est ce que les autres listes déroulantes posent problème

Je peux mettre une taille minimal à la liste mais je voudrais reproduire pour être sur de corriger le problème

**Comment by Chris-afk71** [comment]
Résolution ce sont les paramètres de base, je n'ai rien changé : 
![image](https://user-images.githubusercontent.com/102148143/160253949-143be507-a9f4-4942-bd31-d9b532867159.png)

Oui la fenêtre est ouverte au maxi.

![image](https://user-images.githubusercontent.com/102148143/160254007-4facf54e-c83a-4e69-8d5e-dc924140e675.png)

![image](https://user-images.githubusercontent.com/102148143/160254043-cdc62c3f-3d80-4251-b8cb-114dd62acd04.png)

![image](https://user-images.githubusercontent.com/102148143/160254059-11776bdd-4f24-4e9e-995d-8ae07871def3.png)

**Comment by Jean-Romain** [comment]
J'allais répondre que le texte par defaut à 150% expliquait le problème mais je viens de tester et non... Et bien je ne sais pas. Je vais forcer les listes à être un peu plus grande dans la prochaine version on verra si ça aide.

Je vois aussi un problème d'encodage pour la liste des accordéons

**Comment by Jean-Romain** [comment]
Je pense avoir résolu le problème en reproduisant le comportement par defaut sous linux. Les popups de combobox sont maintenant plus large que la combobox

![Capture](https://user-images.githubusercontent.com/3872279/160277731-34b37153-55f3-4a3c-8e3f-0ba87e84ac86.PNG)
