### ISSUE TITLE
Les accords mineurs ne sont pas parsés

### ISSUE THREAD

**Issue by Jean-Romain** [Jean-Romain/tabliato#2]
Code 

```
p7:4 7:8 6' 8 7' Am
```

Rendu

![Capture d’écran du 2021-06-19 08-57-32](https://user-images.githubusercontent.com/3872279/122643216-9704f880-d0dc-11eb-8a21-f5df24385bc7.png)

Le code `lilypond` produit est incorrect

```
AM r8 am r8 am r8 
```

Et devrait être un truc du genre

```
<a, a>8^"Am" r8 <a c e>8^"am" r8 <a c e>8^"am" r8 
```

**Comment by Jean-Romain** [comment]
Corrigé

![Capture d’écran du 2021-06-19 13-33-29](https://user-images.githubusercontent.com/3872279/122650893-59679600-d103-11eb-86ae-7512cdb65724.png)

@flo-dhalluin Je ne sais pas si ça résout le problème des basses. Sûrement pas le Mib. En fait je ne sais même pas comment le représenter. Je n'ai jamais vu une tablature comme ça. Déjà le  la mineur rendu Am am am, je n'ai jamais vu ça sur une tablature et je ne suis même pas sûr que ça ait du sens puisque la basse c'est juste un la donc j'aurais plutôt envie de produire A am am.

**Comment by flo-dhalluin** [comment]
C'était ma feature request d'après : souvent on met juste l'harmonisation "au dessus" de la portée : c'est assez standard comme notation pense comme si tu mettais des accords pour un guitariste... ( et on laisse A a a dans la tablature peut importe si l'accord est mineur ou non ). 
Petit point "harmonie" : 
Sur un diato 8 basses en G/C , tu n'as qu'un accord mineur : Am tout les autres sont en majeurs. Le problème c'est que ( par exemple ) tu peux très bien jouer en mi-mineur à la main droite, et là ça va gratter... La plupart des accordéons proposent une tirette pour occulter les tierces et donc dénaturer les accords ( un accord sans tierce, c'est ni majeur ni mineur). Sur des accordéons d'entrée de gamme pas de tirette : on finit souvent par juste bloquer les tierces ( morceau de scotch sur les anches par ex, pour mon 2915...) . Mettre l'harmonisation sur la tablature, ça permet de faire figurer des septièmes par ex, qui sont intéressantes pour l'accompagnant aussi ( tu peux faire assez facilement des accords avec septième main droite aussi ).

**Comment by Jean-Romain** [comment]
Il faut plus me montrer des images que de mettre trop de vocabulaire de solfège. Genre je sais de quoi on parle là mais ça m'aide pas plus que ça. Un peu comme un étudiant qui récite un cours un peu trop par cœur.

Pour info il y a 7 ans quand j'ai débuté le projet j'étais en contact avec une personne, même genre que toi, bonne connaissances en diato et prog qui m'a beaucoup apprit  sur le solfège et la construction des diatos (c'est lui qui m'avait expliqué cette histoire d'accord sans tierce et de scotch). Il m'a beaucoup aidé en m'apportant des connaissances sans lesquels plein de choses dans le logiciel ne pourraient pas exister. A la base moi j'avais juste besoin d'un logiciel pour avoir des partitions de qualité `LaTeX/lilypond` (et pas les horribles abominations qu'on trouve ici et là sur internet) pour apprendre le diato. Et le faire à la main non merci j'en ai fait une ou deux mais je préfère passer 7 ans à faire un logiciel :smile: 

En gros pour le dire simplement je pense que la base de code est là pour faire plein de choses mais pour le moment ça n'existe pas forcément car mes connaissance en solfège et en diato ne me permettent pas de me dire *"ha oui on pourrait faire ça aussi"* mais si on me le demande et qu'on me montre à quoi ça doit ressembler je pense que ce n'est pas compliqué à ajouter.

Donc en gros si je comprend bien. C'est ça:

![Capture d’écran du 2021-06-19 16-56-54](https://user-images.githubusercontent.com/3872279/122655327-8164f280-d11f-11eb-9d1e-336ae24c9983.png)
