### ISSUE TITLE
Chargement de l'audio à l'ouverture d'un fichier

### ISSUE THREAD

**Issue by Chris-afk71** [Jean-Romain/tabliato#20]
Quand on ouvre un fichier existant déjà compilé et que l'on lance la lecture audio on reste sur l'avant dernier morceau ouvert, il faut recompiler. C'est normal ?

**Comment by Jean-Romain** [comment]
Normal je ne sais pas disons que je peux améliorer ca,

**Comment by Jean-Romain** [comment]
C'est corrigé pour la prochaine version
