### ISSUE TITLE
Changement de motif

### ISSUE THREAD

**Issue by Chris-afk71** [Jean-Romain/tabliato#22]
Bonjour, j'aimerais reproduire cette partition mais j'ai un problème de syntaxe : 

![image](https://user-images.githubusercontent.com/102148143/160277209-edda57d7-5789-435c-93a9-fe71474ac5b0.png)

J'ai écrit ceci mais ça ne marche pas... Merci pour votre aide.
 
```r
t9':4 9':8 p8' t8' 9 F
7':4 8':8 7' 8' 9' G
p7':4 7':8 6' 7' 6' C
t7:4. 5:8 7 6' A
8:4 8' 9 F

\motif [B:4 a:4. a:4.]

p8:4 6':8 8 6' 7 6' 7 E

\motif [B:4 a:4 a:4]

t7:8 5 7 6' 8 7' A
9 7' 8 7' 9 8' A
```

**Comment by Jean-Romain** [comment]
Je ne comprend pas ce que vous souhaitez faire. La partition que vous me montrez me semble bien normale avec un rythme constant `B a a` à toutes les phrases musicale. Donc il n'y a pas besoin de motif spécial. C'est très rare d'avoir à utiliser `\motif` mais si jamais c'est utile attention on est en 3/4 (je suppose) donc `\motif [B:4 a:4. a:4.]` ce n'est pas possible. On a 3 noires par mesure donc des accords avec 1 noires et deux noires pointée ce n'est pas possible. Un truc valide serait

```ly
\motif [B:2 a:8 a:8]
```

Ca donnerait basse sur une blanche, deux accords sur deux croches c'est correct. De plus change de motif pour une mesure c'est un peu compliqué vous pouvez écrire

```ly
 8:4 8' 9 F

p8:4 6':8 8 6' 7 6' 7 E:2 e:8 e:8

t7:8 5 7 6' 8 7' A
```

On trouve aussi deux notes de trop dans votre exemple, il y a une mesure incomplète.

**Comment by Jean-Romain** [comment]
Ha non j'ai compris c'est la mesure avec deux triolet le problème !

**Comment by Jean-Romain** [comment]
En lilypond un triolet s'ecrit [`\tuplet 3/2`](https://lilypond.org/doc/v2.18/Documentation/learning/advanced-rhythmic-commands.fr.html#tuplets). Essayons

```ly
t9':4 9':8 p8' t8' 9 F
7':4 8':8 7' 8' 9' G
p7':4 7':8 6' 7' 6' C
t7:4. 5:8 7 6' A
8:4 8' 9 F
p8:4 \tuplet 3/2 { 6':8 8 6' } \tuplet 3/2 { 7 6' 7 } E
t7:8 5 7 6' 8 7' A
9 7' 8 7' 9 8' A
```

Oui ca marche je suis surpris moi même :laughing:
