### ISSUE TITLE
Décalage affichage

### ISSUE THREAD

**Issue by Chris-afk71** [Jean-Romain/tabliato#25]
Bonjour,
Version 1.04 installé, ça marche, merci.

J'ai un petit problème d'affichage avec le "4':2" qui dure... et la barre du 10 est décalé 'ou le 10) à priori ça n'est que visuel : 

![image](https://user-images.githubusercontent.com/102148143/162194355-513b4187-492c-47b1-b538-a6e5d65ca4d4.png)

```ly
\repeat volta 2
{
  p7:4 t6 p6 E
  t7 6':4. p5':8 D
  t6:4  p4':2 E
  r:8 p4:8 4' t6 p6 7  E
  t9:4 6' 8 A
  7' 9:4. 8':8 D
  p7':4 7 6 E 
  p4:2 \tuplet 3/2 { 4:8 4' 6 } E

  t7 6 7 6' 8 9 A
  10:2 \tuplet 3/2 { 3':8 6 7 } D
  p7 6 4' 6 7 8 G
  t10:2 \tuplet 3/2 { 3':8 6 7 } D
  p8 7' 8 6' 7 6' G
  t7' 7 6 7 7' 7 D
  p6' 6 7 4' 6 7 E
  7':2 7:4 E
}
\break

\repeat volta 2
{
  t6:8 7 6 3' 6 7 D
  7':2 6':4 D
  p6:4. 7:8 4' 6 E
  7:2 7:4 E
  \tuplet 3/2 { t3':8 6 7 } 8:4 7' D
  10:8 8' 9:4 8 D
  p7:2 7:4 E
  ~ 7:2 7:4 E
  \tuplet 3/2 { t9:8 8 7 } 6 7 6' 8 D
  10:4. 7':8 7 6 D
  p6 4' 4 4' 6 6' G
  t10:4. 3':8 6 7 D
  p8:4. 7:8 6':4 G
  t6 7 6 D
}

\alternative
{
  { p4':2. E ~ 4':2 7:4 E }
  { p6:8 4' 4 4' 6 7 E 7':2. E }
}
```

**Comment by Jean-Romain** [comment]
Ok je confirme que j'ai le même problème je vais regarder. Je pense que je sais quel est le problème. Je pense n'avoir mis aucune règle pour arrêter la barre de tenue sur un silence.

Notez que c'est uniquement un problème de rendu graphique, la partition est correcte et l'audio aussi.

**Comment by Jean-Romain** [comment]
Rien à voir avec le bug rapporté

Je ne sais pas quel accordéon vous utilisez mais cette partition est impossible sur un sol/do 2 rang classique. Le Mi (E) est en poussé uniquement et Ré (D) en tiré uniquement. Donc la première mesure seraient peut être:

```ly
  p7:4 t6 p6 [E a e]
```

La deuxième mesure est correcte si on considère que les accompagnement se jouent sur des croches. C'est ce que joue tabliato même si ce n'est pas visible. Dans un rythme `B a a` on pourrait penser que ce qui est produit ce sont 3 noires mais en fait si vous écoutez bien ce sont 3 croches et trois demi-soupirs. C'est plus dynamique comme façon de jouer. Dans ce cas la deuxième mesure est techniquement jouable. En revanche si on joue moins dynamique et que les basses accords durent une noire chaque ce n'est pas jouable et ça devient peut être:

```ly
  t7 6':4. p5':8 [D d g]
```

Le reste de la tablature est pareil il faut vérifier que ça marche. Ça fait parti des chose que je veux implémenter dans tabliato. Détecter si les accords sont jouables et compatible le sens poussé/tiré

D'ailleurs j'en profite pour expliquer pourquoi dans la partition précédente j'avais écrit

```r
\motif [B:8 r:8 a:8 r:8 a:8 r:8]
```

Et non 

```r
\motif [B:4 a:4 a:4]
```

C'est un choix et c'est ce que fait tabliato par defaut. Mais certaines musiques ne laissent pas vraiment le choix en fait

**Comment by Jean-Romain** [comment]
J'ai corrigé le gros problème de barres de tenu et il me reste à régler finement les marges pour éviter que les boutons 10 et + aient un décalage.

**Comment by Jean-Romain** [comment]
En attendant la version 1.0.5 vous pouvez écrire

```ly
r:8 \stopTextSpan p4:8 4' t6 p6 7  E
```

Ca devrait palier au problème temporairement

**Comment by Chris-afk71** [comment]
Je ne la joue pas celle là, c'est une partition que j'ai récup. je voulais l'essayer dans tabliato.
j'ai oublié de décaler l'armure au g/major par rapport à la partition original.
Une autre question, comment on fait pour ne pas attacher les croches entre elles comme ci dessous ?

![image](https://user-images.githubusercontent.com/102148143/162219245-3d4e9bca-1116-4d0f-8da7-1dad7c363877.png)

**Comment by Jean-Romain** [comment]
J'ai corrigé le décalage des 10. Update demain.
