### ISSUE TITLE
Inversion du sens des notes.

### ISSUE THREAD

**Issue by Chris-afk71** [Jean-Romain/tabliato#26]
En version 1.04 j'ai un soucis que je n'avais pas avant. Il tire les notes alors qu'elles sont en poussées et en bleu. Il faut répéter le "p" maintenant ? Il y a un contrôle en plus ?

```ly
\set Timing.beamExceptions = #'()
\set Timing.beatStructure=1,1,1

\repeat volta 2
{
t9:4. 8':8 9 8
t9:4. 8':8 9 8
9:4 7' 8
p7:2.
p8:4. 7':8 8 7
8:4. 7':8 8 7
8:4 6' 7
t7:2.

A A A E E E E A
}

\break

t5:4 7 6'
8:2 8:4
8 6' 7
p7:2.
4':4 7 6'
8:2 8:4
8 6' 7
t7:2.

A A A E E E E A
\break

\repeat volta 2
{
  t7:4 8 9
  9':2 9':4
  p9':4 t10' 9'
  p7':2 7':4
  p8':4 t8' 7'
  6':2 6':4

A F F C [C g g] G
}

\alternative
{
   { 7':4 8 7' p7' 6' 7 G C}
   { p8:4 6' 7  t7:2. E A}
}

\break

\repeat volta 2
{
  t7:8 6' 8 7' 9:4
  <8' 9'>:2 <8' 9'>:4
  <8' 9'> p<8' 7'> t<7' 8'>
  p<7' 6'>:2 <7' 6'>:4
  <7' 6'> 8 6'
  <7 6>:2 7:4
  <7 6> 6' 8 <7' 6'>:2.

  A F F C [C g g] G G C
}
```

![image](https://user-images.githubusercontent.com/102148143/162225801-1e372b8e-f9ce-468a-b77f-c9d27d77dd59.png)

**Comment by Jean-Romain** [comment]
C'est possible. En fait j'ai changé énormément de code entre 1.0.3 et 1.0.4 en prévision de fonctionnalités future impossible à réaliser sans repenser des trucs. J'ai pu casser quelques choseset je n'ai pas eu le temps de vérifier. Ca ne devrait pas être trop compliqué à réparer. Visible ce sont les accords qui posent problème

**Comment by Jean-Romain** [comment]
C'est corrigé ca ira dans la 1.0.5 (demain pour vous)
