### ISSUE TITLE
Tabliato n'exporte pas en .ly

### ISSUE THREAD

**Issue by agentils** [Jean-Romain/tabliato#4]
J'ai installé le logiciel sur WSL (je n'ai pas trouvé le binaire Windows).

Lorsque je lance l'exportation, tous les formats fonctionnent excepté le format Lilypond. Pourtant le PDF se génère normalement.

Au niveau du cache je ne trouve pas de fichier .ly non plus.

J'aurais voulu récupérer ce format pour essayer de faire des modifications plus fines (ajouter des indications genre > sous une note, indiquer lorsqu'il faut jouer la basse et l'accord en simultané).

**Comment by Jean-Romain** [comment]
Bonjour, il n'y a pas de binaire Window. Ce projet est plus ou moins à l'abandon. Disons qu'il fonctionne pour mes besoins mais j'ai totalement abandonné il y a longtemp le support de Windows. Je confirme que le fichier lilypond est manquant je vais regarder.

**Comment by Jean-Romain** [comment]
J'ai corrigé le problème d'export lilypond. Merci. Comme je l'ai dit le projet est un peu à l'abandon mais si vous êtes interessé ca me fera plaisir de me remettre dessus pour corriger des problèmes et ajouter des fonctionnalités.

> (ajouter des indications genre > sous une note, 

J'ai regardé la doc de lilypond et une accentuation s'écrit `->` donc je pense que le parseur de tabliato ne va pas aimer. Mais ca serait facile à corriger.

> indiquer lorsqu'il faut jouer la basse et l'accord en simultané).

Ca c'était possible avant mais j'ai perdu une partie du code. Il faudrait que je le refasse.

**Comment by Jean-Romain** [comment]
En fait ca marche presque. Il faut juste que je trouve le nom des accentuations dans lilypond pour les cacher sur la deuxième ligne

```
t7:4 8 7' 9:2 9:4 p6 7 -> 6' 8:2 8:4 \accent
```

![Capture d’écran du 2022-01-15 14-54-46](https://user-images.githubusercontent.com/3872279/149635977-6716d4e9-9a29-429d-90fc-11e9e72d4857.png)

**Comment by agentils** [comment]
Merci pour le fix. Du coup je peux bidouiller le fichier .ly
En effet l'accentuation apparaît sur les deux lignes (et il y a également l'indication \mf qui elle apparaît sur les trois lignes). Je pense que ce sont des choses qui ne font pas partie généralement des partitions de diato, mais il se trouve que la première partition que j'ai voulu recopier contient tout ça.

**Comment by Jean-Romain** [comment]
Il suffit de me montrer les problèmes et j'éditerai le template lilypond pour que les indications n'apparaissent pas. Pour les accentuation je n'ai toujours pas trouvé. Si vous même êtes connaisseur de lilypond le template est [ici](https://github.com/Jean-Romain/tabliato/blob/master/share/templates/tabliato.ly). Le template est rempli par tabliato. Il faut changer le context [`diatoButtonSetup`](https://github.com/Jean-Romain/tabliato/blob/a3c52a3e31c5f48446ca3bc72d68a5ce297e3cb9/share/templates/tabliato.ly#L452) et trouver les noms des propriétés des accentutations et autres trucs qui ne doivent pas être affichés.

**Comment by agentils** [comment]
Ca a été compliqué mais j'ai fini par trouver : la ligne `\override Script #'stencil = ##f` permet d'empêcher l'affichage des signes d'articulation. Je suis en train de découvrir Lilypond en même temps que Tabliato. La doc de Lilypond est riche mais j'ai du mal à trouver les infos.
J'ai également ajouté `\override DynamicText #'stencil = ##f` pour ne pas avoir les nuances affichées sur toutes les lignes.
Merci pour votre aide et votre réactivité.

**Comment by Jean-Romain** [comment]
Super merci j'ai ajouté ces deux lignes dans le template.

> La doc de Lilypond est riche mais j'ai du mal à trouver les infos.

Oui lilypond est aussi extraordinaire que inbuvable :wink:
