### ISSUE TITLE
Ouverture des fichiers .dtb sous Window 11

### ISSUE THREAD

**Issue by Hant65** [Jean-Romain/tabliato#40]
Bonjour, 
Je ne sais pas si la fonction a été prévue, mais, sous Windows 11, le "double clic" sur les fichiers .dtb ne permet pas de les ouvrir ; ils ont pourtant été préalablement déclarés comme devant être ouverts avec Tabliato. 
Curieusement, lors du double clic, on voit brièvement se créer un fichier .ly, qui disparaît ensuite spontanément. 
Cdt

**Comment by Jean-Romain** [comment]
Oui je sais, c'est prévu pour la prochaine version. Ouvrir un fichier par double clic ne se fait pas automatiquement, il faut que le logiciel ait prévu la fonctionnalité. Hors la fonctionnalité actuelle c'est de produire la tablature. Mais dans la version en développement c'est déjà fait.

**Comment by Jean-Romain** [comment]
C'est gentil merci mais si vous me répondez par email avec une pièce jointe ca n'arrive pas jusqu'ici sur github :wink:

**Comment by Hant65** [comment]
Bon, mais c'est que je ne voulais pas démarrer un fil de discussion pour cela. Vous aurez compris que je ne suis pas familier des plate-formes. Mais si vous me dites comment faire, pas de problème. Par ailleurs, avez vous des préférences pour tel ou tel type de morceau ? Je ne voudrais pas non plus vous encombrer ... 


     Le jeudi 16 février 2023, 21:54:34 UTC+1, Jean-Romain ***@***.***> a écrit :  
 
 


C'est gentil merci mais si vous me répondez par email avec une pièce jointe ca n'arrive pas jusqu'ici sur github 😉

**Comment by Jean-Romain** [comment]
En pièce jointe dans un zip depuis le site github.com et pas depuis les emails. En fait vous recevez des emails de notifications parce que j'ai répondu. Par la magie de je ne sais quelle système informatique vous pouvez me répondre directement par email ca ajoute votre message sur github.com mais les pièces jointe ne parviennent pas comme le texte.

Sinon vous pouvez m'écrire à jromain.roussel [@] gmail.com

> Par ailleurs, avez vous des préférences pour tel ou tel type de morceau ? Je ne voudrais pas non plus vous encombrer.

Aucun problème c'est à votre guise. Je suis content que vous partagiez les tablatures, plus j'en ai plus tabliato deviendra (peut être) populaire.

**Comment by Hant65** [comment]
Bon, la voici. Si vous ne parlez pas le gascon, voyez son sous-titre : elle date du temps d'avant le "travailler plus pour..."
Bonne soirée !
[Quoan vols ganhar.zip](https://github.com/Jean-Romain/tabliato/files/10760930/Quoan.vols.ganhar.zip)
