### ISSUE TITLE
Indication de doigté

### ISSUE THREAD

**Issue by nmetifiot** [Jean-Romain/tabliato#44]
![Capture d’écran du 2024-01-28 12-50-51](https://github.com/Jean-Romain/tabliato/assets/11557541/7436e241-1bbb-4361-bc1a-4259ae6aa31a)
Bonjour, 
J'aimerais utiliser la fonctionnalité de l'indication du doigté, malheureusement la marque ne s'affiche pas dans la pré-visualisation.
Est-ce que j'utilise la bonne syntaxe ?

**Comment by Jean-Romain** [comment]
Je confirme que ca devrait marcher mais que ca ne marche pas/plus. Je vais chercher pour comprendre et corriger.

**Comment by Jean-Romain** [comment]
J'ai identifié le problème. Je vais sortir une nouvelle version corrigée. Dans la semaine.

**Comment by Jean-Romain** [comment]
Voici une pre-version `1.3.4` avec le bug corrigé. Je ne suis plus capable de faire une version Windows alors je ferai une release plus tard quand je serai de nouveau capable de produire la version Windows.

J'ai renommé `tabliato.deb` en `tabliato.zip` pour que github accepte l'upload mais c'est bien un paquet debian. Ne dezippez pas et changez l'extension de fichier avant de l'installer.

[tabliato.zip](https://github.com/Jean-Romain/tabliato/files/14077425/tabliato.zip)

**Comment by nmetifiot** [comment]
merci ça fonctionne très bien :+1:
