### ISSUE TITLE
Nouvelle fonctionnalité accompagnement simultané

### ISSUE THREAD

**Issue by nmetifiot** [Jean-Romain/tabliato#45]
Bonjour.
Est-il possible d'ajouter une nouvelle fonctionnalité ? J'aimerais pouvoir écrire un accompagnement simultané.
Par exemple un A juste au dessus d'un a.
Comme ce que vous avez fait pour faire un accord avec les notes.

**Comment by Jean-Romain** [comment]
C'est déjà la fonctionnalité demandée en #15. Si ce n'est toujours pas fait c'est que c'est plus compliqué que ca en a l'air. En fait je n'ai pas réussi à le faire. Mais je n'oublie pas que j'aimerais le faire.

Savoir que des gens utilisent le logiciel peut me motiver à réfléchir à la question, mais ayez peu d'espoir à court terme. 

Je ferme, il y a déjà une issue ouverte sur ça.

**Comment by nmetifiot** [comment]
Merci beaucoup en tout cas pour tout ces échanges 😄
