### ISSUE TITLE
g# (1' button in CADB convention) printed one octave lower than it should on musical stave

### ISSUE THREAD

**Issue by tonioker** [Jean-Romain/tabliato#5]
Hi, I'm very happy with tabliato, I just started to use it and find it quite user friendly.
I just noticed one bug, which is that g# (P1' ) is printed one octave lower than it should on musical stave.
Same thing for T1' (a#).
I did not search in the code, in case it's easy to correct for you .
Thanks again for this wonderfull tool

**Comment by Jean-Romain** [comment]
Hi,

I'm not sure to understand what is the problem. It looks good to me.

```
p1' p2' p3' p4' p5' p6' 
t1' t2' t3' t4' t5' t6' 
```
![Capture d’écran du 2022-01-27 17-59-20](https://user-images.githubusercontent.com/3872279/151457344-451a740a-5fe1-43ae-b22d-d8e804c097de.png)

Or maybe you are using another keyboard ?

**Comment by tonioker** [comment]
I guest I did not configured the keyboard . I ll check and keep you informed. Thank a lot for your answer !

⁣Télécharger BlueMail pour Android ​

Le 28 janv. 2022 à 00:04, à 00:04, Jean-Romain ***@***.***> a écrit:

**Comment by Jean-Romain** [comment]
The default is a 2 rank G/C which is the most standard option for beginners. But 12 keyboards are recorded including 3 ranks, A/D and so on. I'm not excluding some error in other keyboards as I never used them.
